server:
  port: 48011


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE:springboot_demo}
    username: ${MYSQL_USERNAME}
    password: ${MySQL_PASSWORD}
    initialize: false
    continue-on-error: true
  mvc:
    view:
      suffix: .html
      prefix: /

#mybatis:
#  mapper-locations: classpath*:mapper/*Mapper.xml
